version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/home/tiago-sales/git/database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
volumes:
  db_data: